### PR TITLE
adds stars to terra conversions

### PR DESCRIPTION
**Pull request by Nowosad**
I mostly readapt the `st_as_raster` code:

``` r
library(stars)
library(terra)
tif = system.file("tif/L7_ETMs.tif", package = "stars")

# nonproxy
x = read_stars(tif)
xt = as(x, "Terra")
xt
#> class       : SpatRaster 
#> dimensions  : 352, 349, 6  (nrow, ncol, nlyr)
#> resolution  : 28.5, 28.5  (x, y)
#> extent      : 288776.3, 298722.8, 9110729, 9120761  (xmin, xmax, ymin, ymax)
#> coord. ref. : +proj=utm +zone=25 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
#> source      : memory 
#> names       : band1, band2, band3, band4, band5, band6 
#> min values  :    47,    32,    21,     9,     1,     1 
#> max values  :   255,   255,   255,   255,   255,   255

# proxy
x2 = read_stars(tif, proxy = TRUE)
xt2 = as(x2, "Terra")
xt2
#> class       : SpatRaster 
#> dimensions  : 352, 349, 6  (nrow, ncol, nlyr)
#> resolution  : 28.5, 28.5  (x, y)
#> extent      : 288776.3, 298722.8, 9110729, 9120761  (xmin, xmax, ymin, ymax)
#> coord. ref. : +proj=utm +zone=25 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
#> source      : L7_ETMs.tif 
#> names       : L7__1, L7__2, L7__3, L7__4, L7__5, L7__6

# categorical -------------------------------------------------------------
tf = tempfile(fileext = ".zip")
td = tempdir()
download.file("https://github.com/r-spatial/stars/files/4345255/lanform-example.zip", tf)
unzip(tf, exdir = td)
lf_path = paste0(td, "/lanform.tif")

# nonproxy
lf1 = read_stars(lf_path, proxy = FALSE)
lf1t = as(lf1, "Terra")
lf1t
#> class       : SpatRaster 
#> dimensions  : 3812, 7360, 1  (nrow, ncol, nlyr)
#> resolution  : 300, 300  (x, y)
#> extent      : -1091676, 1116324, -1182156, -38556.49  (xmin, xmax, ymin, ymax)
#> coord. ref. : +proj=cea +lat_ts=5.5 +lon_0=140.8 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs 
#> source      : memory 
#> name        :                         lyr.1 
#> min value   : 1. Flat or nearly flat plains 
#> max value   :    9. Scattered low mountains

# proxy
lf2 = read_stars(lf_path, proxy = TRUE)
lf2t = as(lf2, "Terra")
lf2t
#> class       : SpatRaster 
#> dimensions  : 3812, 7360, 1  (nrow, ncol, nlyr)
#> resolution  : 300, 300  (x, y)
#> extent      : -1091676, 1116324, -1182156, -38556.49  (xmin, xmax, ymin, ymax)
#> coord. ref. : +proj=cea +lat_ts=5.5 +lon_0=140.8 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs 
#> source      : lanform.tif 
#> name        :                      category 
#> min value   : 1. Flat or nearly flat plains 
#> max value   :    9. Scattered low mountains
```

<sup>Created on 2021-08-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### CODE REVIEW

**Comment by Nowosad** [comment]
Updates:

``` r
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.9.0, GDAL 3.2.2, PROJ 7.2.1
#> Registered S3 methods overwritten by 'stars':
#>   method             from
#>   st_bbox.SpatRaster sf  
#>   st_crs.SpatRaster  sf
library(terra)
#> terra version 1.4.11
tif = system.file("tif/L7_ETMs.tif", package = "stars")

# nonproxy
s = read_stars(tif)

xt = as(s, "SpatRaster")
xt
#> class       : SpatRaster 
#> dimensions  : 352, 349, 6  (nrow, ncol, nlyr)
#> resolution  : 28.5, 28.5  (x, y)
#> extent      : 288776.3, 298722.8, 9110729, 9120761  (xmin, xmax, ymin, ymax)
#> coord. ref. : UTM Zone 25, Southern Hemisphere 
#> source      : memory 
#> names       : band1, band2, band3, band4, band5, band6 
#> min values  :    47,    32,    21,     9,     1,     1 
#> max values  :   255,   255,   255,   255,   255,   255

terra::plot(xt)
```



``` r
# proxy
s2 = read_stars(tif, proxy = TRUE)
xt2 = as(s2, "SpatRaster")
xt2
#> class       : SpatRaster 
#> dimensions  : 352, 349, 6  (nrow, ncol, nlyr)
#> resolution  : 28.5, 28.5  (x, y)
#> extent      : 288776.3, 298722.8, 9110729, 9120761  (xmin, xmax, ymin, ymax)
#> coord. ref. : UTM Zone 25, Southern Hemisphere 
#> source      : L7_ETMs.tif 
#> names       : L7__1, L7__2, L7__3, L7__4, L7__5, L7__6

terra::plot(xt2)
```



``` r
# categorical -------------------------------------------------------------
tf = tempfile(fileext = ".zip")
td = tempdir()
download.file("https://github.com/r-spatial/stars/files/4345255/lanform-example.zip", tf)
unzip(tf, exdir = td)
lf_path = paste0(td, "/lanform.tif")

# nonproxy
lf1 = read_stars(lf_path, proxy = FALSE)
lf1t = as(lf1, "SpatRaster")
lf1t
#> class       : SpatRaster 
#> dimensions  : 3812, 7360, 1  (nrow, ncol, nlyr)
#> resolution  : 300, 300  (x, y)
#> extent      : -1091676, 1116324, -1182156, -38556.49  (xmin, xmax, ymin, ymax)
#> coord. ref. : +proj=cea +lat_ts=5.5 +lon_0=140.8 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs 
#> source      : memory 
#> name        :                         lyr.1 
#> min value   : 1. Flat or nearly flat plains 
#> max value   :    9. Scattered low mountains

terra::plot(lf1t)

# proxy
lf2 = read_stars(lf_path, proxy = TRUE)
lf2t = as(lf2, "SpatRaster")
lf2t
#> class       : SpatRaster 
#> dimensions  : 3812, 7360, 1  (nrow, ncol, nlyr)
#> resolution  : 300, 300  (x, y)
#> extent      : -1091676, 1116324, -1182156, -38556.49  (xmin, xmax, ymin, ymax)
#> coord. ref. : +proj=cea +lat_ts=5.5 +lon_0=140.8 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs 
#> source      : lanform.tif 
#> name        :                      category 
#> min value   : 1. Flat or nearly flat plains 
#> max value   :    9. Scattered low mountains

terra::plot(lf2t)
```



``` r
# back to start -----------------------------------------------------------
ns1 = st_as_stars(xt)
plot(ns1)
```



``` r
ns2 = st_as_stars(xt2)
plot(ns2)
```



``` r
ns3 = st_as_stars(lf1t)
plot(ns3)
#> downsample set to 8
```



``` r
ns4 = st_as_stars(lf2t)
plot(ns4)
#> downsample set to 8
```



<sup>Created on 2021-10-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Nowosad** [comment]
New changes:

1. I used `SpatRaster` instead of `Terra`.
2. I created two helper functions used for both raster and terra objects - `st_as_raster()` and `fix_dims()`.
3. I added some tests.
4. I added a new `st_as_stars()` function for `SpatRaster` objects (previously, this conversion was done by the conversion to raster first). 
5. I think that, in the future, separate conversion functions for **raster** could be replaced by means of using the **terra** conversions (as **raster** imports **terra** now). 
6. I have not added `as(x, "RasterBrick")` and `as(x, "RasterStack")` yet as I am unsure how these functions should look like. Should I just another several lines of code like the one below or is there a more compact way to reuse the `as` function?

```r
setAs("stars", "RasterBrick", function(from) {
	if (!requireNamespace("sp", quietly = TRUE))
		stop("package sp required, please install it first") # nocov
	if (!requireNamespace("raster", quietly = TRUE))
		stop("package raster required, please install it first") # nocov
	if (!is_regular_grid(from))
		stop("only regular rasters can be converted to Raster* objects")
	st_as_raster(from, class = "Raster")
})
```

**Comment by edzer** [comment]
> there is a RasterStackBrick class

@tim-salabim I think that is meant to write methods for that should work for both stack&brick, but is not meant to be instantiated.

**Comment by edzer** [comment]
Thanks, great work!

**Pull request merged**
