### PR TITLE
R netcdf-1

### PR DESCRIPTION
**Pull request by mdsumner**
Remove dependence on ncdf4 in favour of RNetCDF. 

(@edzer  apologies for noise previously). 

@dblodgett-usgs also sorry I should have paid more attention over xmas (or none at all!) - I'm carefully reviewing PR #88 now, there were a few things I should have picked up on.

### CODE REVIEW

**Comment by edzer** [comment]
Another issue with RNetCDF is this:
```r
> library(RNetCDF)
> library(units)
udunits system database from /home/edzer/R/x86_64-pc-linux-gnu-library/3.5/RNetCDF/udunits
Warning message:
In .get_ud_xml_dir(TRUE) :
  multiple udunits databases present: /home/edzer/R/x86_64-pc-linux-gnu-library/3.5/RNetCDF/udunits/udunits2.xml /usr/share/xml/udunits/udunits2.xml
```
i.e. RNetCDF sets its own environment variable without checking any system defaults. I guess I have to figure that out with the RNetCDF folks.

**Comment by dblodgett-usgs** [comment]
@mdsumner - let me know if there is anything I can fix here. I am back working and have time to help as needed.

**Comment by dblodgett-usgs** [comment]
Curvilinear test contributed over here: https://github.com/mdsumner/stars/pull/1

**Comment by edzer** [comment]
Ready to merge, but just to make sure: this PR works with CRAN versions of dependencies, right?

**Comment by mdsumner** [comment]
Yes - all CRAN - I just extra-checked, and pushed some clean ups in the doc with @dblodgett-usgs's new files and tests.  Passing travis on release and devel.

**Comment by mdsumner** [comment]
👌

**Pull request merged**
