### PR TITLE
update CI workflows

### PR DESCRIPTION
**Pull request by kadyb**
1. Move the `pkgdown` build and `test-coverage` to separate workflows.
2. Replace tic `rcmdcheck` with RStudio workflow (now it is simplified and similar to `{sf}`). Test package also on Windows and macOS.

I suggest combining all these commits into one.

### CODE REVIEW

**Comment by edzer** [comment]
Does the pkgdown download starsdata, so that https://r-spatial.github.io/stars/articles/stars2.html is rendered the way it is now, with `starsdata` present?

**Comment by kadyb** [comment]
Yes, `pkgdown` downloads `starsdata`:

https://github.com/r-spatial/stars/pull/647/files#diff-5b0fa7342eba196b56e4e0e540a1c68554760fb2c301ddee2e1a7a5848401364R32

But didn't it work before?

https://github.com/r-spatial/stars/pull/647/files#diff-79567d0c6f34621b98467ea7b40a018302e361611bef643f7926a3b823e6df88L85-L89

**Comment by edzer** [comment]
Fantastic, thanks!

**Comment by kadyb** [comment]
One more thing to think about. Maybe in order not to overload the `cran.uni-muenster.de` server, we should skip downloading `starsdata` and checking the vignettes in `rcmdcheck`?

**Comment by edzer** [comment]
Don't worry about that one ;-)

**Pull request merged**
