### PR TITLE
add section about parallel predict to vignette 7

### PR DESCRIPTION
**Pull request by kadyb**

### CODE REVIEW

**Comment by kadyb** [comment]
At this moment, one error:

> Quitting from lines 324-330 (stars7.Rmd) 
> Error: Error: processing vignette 'stars7.Rmd' failed with diagnostics:
> 4 simultaneous processes spawned

and two notes:

>   checking for unstated dependencies in vignettes ... NOTE
>   'library' or 'require' calls not declared from:
>     ‘doParallel’ ‘foreach’

>   checking for non-standard things in the check directory ... NOTE
>   Found the following files/directories:
>     ‘doParallel’ ‘foreach’ ‘iterators’

Maybe we should not execute code after line 319?

**Comment by kadyb** [comment]
@edzer, what do you think?

**Comment by edzer** [comment]
I keep getting errors on R CMD check of this kind:
```

--- re-building ‘stars7.Rmd’ using rmarkdown
Quitting from lines 320-325 (stars7.Rmd) 
Error: processing vignette 'stars7.Rmd' failed with diagnostics:
4 simultaneous processes spawned
--- failed re-building ‘stars7.Rmd’

```

**Comment by edzer** [comment]
I added https://github.com/r-spatial/stars/commit/526c32c1214b5ce8b39385575bf4ba75d3dc5a45 to make things run, simpler, and avoiding making directories.

**Comment by kadyb** [comment]
> I keep getting errors on R CMD check of this kind:

Now I see that. There is also maximum limit of two cores on CRAN: "_If running a package uses multiple threads/cores it must never use more than two simultaneously_" (https://cran.r-project.org/web/packages/policies.html).

**Comment by edzer** [comment]
Ah, I missed that. In any case, with `eval=TRUE` in these sections the package checking duration becomes too long for me to be of practical use (I try to run R CMD check before pushing a commit).

**Comment by edzer** [comment]
Maybe we can make it run only on GH CI, as that is where the vignettes are rendered for the pkgdown site - that is, if that doesn't cause a timeout!

**Comment by kadyb** [comment]
> Maybe we can make it run only on GH CI, as that is where the vignettes are rendered for the pkgdown site - that is, if that doesn't cause a timeout!

I do not know how to do this. From what I can see, completely different vignette (placeholder) is sent on CRAN (https://cran.r-project.org/web/packages/stars/vignettes/stars7.html) than what is in the repository?

In my `{rgugik}` package we precompile the vignettes (https://github.com/kadyb/rgugik/tree/master/vignettes), but this is quite cumbersome and we have to do it manually.

**Comment by edzer** [comment]
> I do not know how to do this. From what I can see, completely different vignette (placeholder) is sent on CRAN (https://cran.r-project.org/web/packages/stars/vignettes/stars7.html) than what is in the repository?

Maybe with `Sys.getenv("USER")=="username_on_GH"`? The placeholders are there because the vignettes get bloated with JS frameworks when rendered nicely, and CRAN doesn't want source packages over 5 Mb without a good reason.

**Comment by kadyb** [comment]
I changed the number of cores from 4 to 2, so it should be ok on `rcmdcheck`. On CRAN it won't be a problem at all, because we don't send that vignette there, right?

**Comment by kadyb** [comment]
BTW: Do you think that instead of using `%dopar%` it would be possible to use `future.apply`? Personally, I don't know how to do it, because a loop with parallel raster processing seems complicated to me to use `apply`, but maybe it is feasible?

**Pull request closed without merging**
