### PR TITLE
ncmeta 0.0.3 dependency

### PR DESCRIPTION
**Pull request by mdsumner**
Improvements in `ncmeta 0.0.3` (now on CRAN) were assumed in the `read_ncdf` function, this PR adds that dependency explicitly

### CODE REVIEW

**Comment by edzer** [comment]
We now see
```r
  Running ‘nc.R’
  Comparing ‘nc.Rout’ to ‘nc.Rout.save’ ...233,240c233,240
<       sst            anom               err             ice       
<  Min.   :-1.80   Min.   :-10.160   Min.   :0.110   Min.   :0.010  
<  1st Qu.:-0.03   1st Qu.: -0.580   1st Qu.:0.160   1st Qu.:0.470  
<  Median :13.65   Median : -0.080   Median :0.270   Median :0.920  
<  Mean   :12.99   Mean   : -0.186   Mean   :0.263   Mean   :0.718  
<  3rd Qu.:24.81   3rd Qu.:  0.210   3rd Qu.:0.320   3rd Qu.:0.960  
<  Max.   :32.97   Max.   :  2.990   Max.   :0.840   Max.   :1.000  
<  NA's   :4448    NA's   :4448      NA's   :4448    NA's   :13266  
---
>      anom               err             ice             sst       
>  Min.   :-10.160   Min.   :0.110   Min.   :0.010   Min.   :-1.80  
>  1st Qu.: -0.580   1st Qu.:0.160   1st Qu.:0.470   1st Qu.:-0.03  
>  Median : -0.080   Median :0.270   Median :0.920   Median :13.65  
>  Mean   : -0.186   Mean   :0.263   Mean   :0.718   Mean   :12.99  
>  3rd Qu.:  0.210   3rd Qu.:0.320   3rd Qu.:0.960   3rd Qu.:24.81  
>  Max.   :  2.990   Max.   :0.840   Max.   :1.000   Max.   :32.97  
>  NA's   :4448      NA's   :4448    NA's   :13266   NA's   :4448   
267,274c267,274
<       sst             anom                err             ice        
<  Min.   :-1.390   Min.   :-1.07000   Min.   :0.300   Min.   :0.0100  
<  1st Qu.:-0.720   1st Qu.:-0.36250   1st Qu.:0.300   1st Qu.:0.1100  
<  Median :-0.515   Median : 0.19500   Median :0.300   Median :0.1700  
<  Mean   :-0.534   Mean   : 0.05867   Mean   :0.303   Mean   :0.2094  
<  3rd Qu.:-0.275   3rd Qu.: 0.55500   3rd Qu.:0.300   3rd Qu.:0.2550  
<  Max.   : 0.030   Max.   : 0.92000   Max.   :0.320   Max.   :0.5200  
<  NA's   :90       NA's   :90         NA's   :90      NA's   :104     
---
>      anom                err             ice              sst        
>  Min.   :-1.07000   Min.   :0.300   Min.   :0.0100   Min.   :-1.390  
>  1st Qu.:-0.36250   1st Qu.:0.300   1st Qu.:0.1100   1st Qu.:-0.720  
>  Median : 0.19500   Median :0.300   Median :0.1700   Median :-0.515  
>  Mean   : 0.05867   Mean   :0.303   Mean   :0.2094   Mean   :-0.534  
>  3rd Qu.: 0.55500   3rd Qu.:0.300   3rd Qu.:0.2550   3rd Qu.:-0.275  
>  Max.   : 0.92000   Max.   :0.320   Max.   :0.5200   Max.   : 0.030  
>  NA's   :90         NA's   :90      NA's   :104      NA's   :90      
```
suggesting that with the new ncmeta the array order is inverted. Or is this the "correct" order?

**Comment by mdsumner** [comment]
That was the difference, variables coming out in alphabetical order rather than native.Will have a closer look at the comparison

**Comment by mdsumner** [comment]
This is expected, native order is sst, anom, err, ice - as gdal sees.

**Comment by edzer** [comment]
Thanks, sorry for the noise - I mixed up the `>` and `<` once more.

**Pull request merged**
