### PR TITLE
Transform wiki page as vignette

### PR DESCRIPTION
**Pull request by statnmap**
Here is a first version of the vignette, directly built from the Wiki.  
It may have to be updated. Proposing this as a vignette will help collaborating on updating the content.  
Proposed in issue https://github.com/r-spatial/stars/issues/122

### CODE REVIEW

**Comment by statnmap** [comment]
I do not get why appveyor is running as there is no appveyor.yml in your repository.  
And the failing CI for Windows with Github Actions is due to problem installing {starsdata}. I assume that re-running the job should work. 
```
cannot open compressed file 'starsdata/DESCRIPTION', probable reason 'No such file or directory'
```

**Comment by edzer** [comment]
Great, thanks a lot!! @pat-s any idea why the tic-windows error occurs?

**Comment by pat-s** [comment]
The windows failure looks random judging from the recent builds.

You need to remove the project on Appveyor manually to remove the hook (or remove the repo from the GitHub Integration).

**Comment by edzer** [comment]
You're right, all gone now - thanks!

**Pull request merged**
