### PR TITLE
allow writing subsetted rasters with stars_proxy objects

### PR DESCRIPTION
**Pull request by ErickChacon**
I had some problems trying to write spatially subsetted `stars_proxy` objects. I made some changes to differentiate the indices of the `stars_proxy` object to be read and the indices of the `stars_proxy` object to be writen. It worked for my case, but I am not sure if this is the approach you would like to take, so I am just opening this pull request to call the attention on this issue.

### CODE REVIEW

**Comment by edzer** [comment]
Great! Does it still work as it did for non-subsetted `stars_proxy` objects?

**Comment by ErickChacon** [comment]
Yes, it works for subsetted and non-subsetted `stars_proxy` objects. In the case of non-subsetted objects, there is no need to differentiate between indices to write and read, but I am still computing them because the algorithm works for both. Maybe, we could add a conditional to differentiate between subsetted and non-subsetted objects (not sure if useful). It would also be good to add a test for this function. Let me know, if I can help with that.

**Comment by edzer** [comment]
No, I like code that works for every case, even if it is harder to read. If you could provide a simple demo, e.g. using the L7 sample data set, that would be perfect.

**Comment by ErickChacon** [comment]
- Below is a simple example. A am using `chunk_size` to test chunk writing.

```r
library(stars)
tif = system.file("tif/L7_ETMs.tif", package = "stars")
l7 = read_stars(tif, proxy = TRUE)
bb = st_bbox(c(xmin = 290000, ymin = 9113000, xmax = 293000, ymax = 9116000), crs = st_crs(l7))
l7_subet = l7[bb]
tmp_file = tempfile(fileext = ".TIF")
write_stars(l7_subet, tmp_file, chunk_size = c(101, 30))
l7_new <- read_stars(tmp_file, proxy = TRUE)
plot(l7_new)
```
Previous output was:
subset_old

New output is:
subset_new

- Subsetting some bands also work:
```r
l7_subet = l7[, 100:200, 150:250, 3:4]
tmp_file = tempfile(fileext = ".TIF")
write_stars(l7_subet, tmp_file, chunk_size = c(101, 30))
l7_new <- read_stars(tmp_file, proxy = TRUE)
plot(l7_new)
```
subset_new2

**Notes:**  I possibly found two bugs while I was doing the examples:
- subsetting operator is not working if range of the index is not defined.
```r
l7_subet = l7[, 100:200, 150:250, ]
# Error in eval(expr) : argument is missing, with no default
```
- In cases where the `stars_proxy` object is smaller than the chunk size. It uses directly `write_stars` and `st_as_stars`:

https://github.com/r-spatial/stars/blob/dbaecb9ae82bc1942ba8e449016cd963b0a68557/R/write.R#L75-L76

This returns the following error when bands were also subsetted:

```r
l7_subet = l7[, 100:200, 150:250, 3:4]
tmp_file = tempfile(fileext = ".TIF")
write_stars(l7_subet, tmp_file)
# Error in sf::gdal_write(obj, ..., file = dsn, driver = driver, options = options,  :
#                         dimensions don't match
```

**Comment by ErickChacon** [comment]
I just noticed that the second bug can be fixed by removing lines:
https://github.com/r-spatial/stars/blob/dbaecb9ae82bc1942ba8e449016cd963b0a68557/R/write.R#L74-L78

**Comment by edzer** [comment]
Thanks a lot! This took a while, in the end I modified it manually. Thanks also for noting the bugs; the third is still present, I believe the others have been resolved in the meantime.

**Comment by ErickChacon** [comment]
Great to see that this functionality is now on the master branch! I will be useful for my work. Thanks!

**Pull request closed without merging**
