### PR TITLE
fix issue where ncsub[, "count"] is NA is being ignored

### PR DESCRIPTION
**Pull request by btupper**
The documentation for `read_ncdf` argument `ncsub` has a note, "If the count value is NA then all steps are included." I assume that is interpreted per dimension.  The current version seems to ignore NA values and throws an error.  This pull request adds a check for NAs in the `count` column of `ncsub` and replaces missing values with the full dimension length as appropriate.

Current version:
```
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
uri <- "http://nomads.ncep.noaa.gov:80/dods/nam/nam20210303/nam_00z"
z = read_ncdf(uri,
              var = "tmpprs",
              ncsub = cbind(start = c(1, 1, 1, 4),
                            count = c(NA, NA, 5, 3)))
#> No projection information found in nc file. 
#>  Coordinate variable units found to be degrees, 
#>  assuming WGS84 Lat/Lon.
#> Error in if (any(ncsub[, "start"] < 1) || any((ncsub[, "count"] - ncsub[, : missing value where TRUE/FALSE needed
```

Proposed pull request:
```
devtools::load_all("~/Dropbox/code/R/packages/stars")
#> Loading stars
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
#> in method for 'coerce' with signature '"stars","Raster"': no definition for class "Raster"
#> in method for 'coerce' with signature '"stars_proxy","Raster"': no definition for class "Raster"
#> in method for 'coerce' with signature '"stars","Spatial"': no definition for class "Spatial"
#> in method for 'coerce' with signature '"stars","STFDF"': no definition for class "STFDF"
uri <- "http://nomads.ncep.noaa.gov:80/dods/nam/nam20210303/nam_00z"
z = read_ncdf(uri,
              var = "tmpprs",
              ncsub = cbind(start = c(1, 1, 1, 4),
                            count = c(NA, NA, 5, 3)))
#> No projection information found in nc file. 
#>  Coordinate variable units found to be degrees, 
#>  assuming WGS84 Lat/Lon.
z
#> stars object with 4 dimensions and 1 attribute
#> attribute(s), summary of first 1e+05 cells:
#>     tmpprs      
#>  Min.   :281.8  
#>  1st Qu.:286.9  
#>  Median :291.1  
#>  Mean   :290.8  
#>  3rd Qu.:293.8  
#>  Max.   :308.1  
#>  NA's   :52474  
#> dimension(s):
#>      from  to                  offset   delta  refsys point
#> lon     1 913                      NA      NA  WGS 84    NA
#> lat     1 443                      NA      NA  WGS 84    NA
#> time    1   3 2021-03-02 22:30:00 UTC 3 hours POSIXct    NA
#> lev     1   5                      NA     -25      NA    NA
#>                           values    
#> lon  [913] -152.879,...,-49.4726 [x]
#> lat    [443] 12.2199,...,61.2056 [y]
#> time                        NULL    
#> lev                         NULL
```

### CODE REVIEW

**Comment by edzer** [comment]
@dblodgett-usgs or @mdsumner would you mind looking into this one?

**Comment by mdsumner** [comment]
Looks fine to me! Vaguely recall not doing this property ...

**Comment by btupper** [comment]
Speaking of vague, is `count` relative to the `start`?  I think it must be, in which case perhaps it should be accounting for `start`?  Like this?

```if (any(ix))  ncsub[ix, "count"] <- dims$length[ix] - ncsub[ix, "start"] + 1```

My thinking is fuzzy on this - I wish I had caught that earlier.

**Comment by btupper** [comment]
Yes, the most recent [commit](https://github.com/r-spatial/stars/pull/394/commits/4f97b9a239bb0bdfe980c2d3fc0c88f6376e14cb) resolves cases when `start` is not at the first index.  Phew.

``` r
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
date <- format(Sys.Date()-1, "%Y%m%d")
uri <- sprintf("http://nomads.ncep.noaa.gov:80/dods/nam/nam%s/nam_00z", date)
z1 = read_ncdf(uri,
              var = "tmpprs",
              ncsub = cbind(start = c(1, 1, 1, 4),
                            count = c(NA, NA, 5, 3)))
#> No projection information found in nc file. 
#>  Coordinate variable units found to be degrees, 
#>  assuming WGS84 Lat/Lon.
z1
#> stars object with 4 dimensions and 1 attribute
#> attribute(s), summary of first 1e+05 cells:
#>     tmpprs      
#>  Min.   :284.3  
#>  1st Qu.:290.6  
#>  Median :294.2  
#>  Mean   :293.5  
#>  3rd Qu.:296.1  
#>  Max.   :306.0  
#>  NA's   :52474  
#> dimension(s):
#>      from  to offset   delta  refsys point                      values x/y
#> lon     1 913     NA      NA  WGS 84    NA [913] -152.879,...,-49.4726 [x]
#> lat     1 443     NA      NA  WGS 84    NA   [443] 12.2199,...,61.2056 [y]
#> lev     1   5 1012.5     -25      NA    NA                        NULL    
#> time    1   3   <NA> NA secs POSIXct    NA                        NULL

z2 = read_ncdf(uri,
                 var = "tmpprs",
                 ncsub = cbind(start = c(700, 400, 1, 4),
                               count = c(NA, NA, 5, 3)))
#> No projection information found in nc file. 
#>  Coordinate variable units found to be degrees, 
#>  assuming WGS84 Lat/Lon.
z2
#> stars object with 4 dimensions and 1 attribute
#> attribute(s):
#>     tmpprs      
#>  Min.   :236.9  
#>  1st Qu.:244.8  
#>  Median :246.8  
#>  Mean   :251.0  
#>  3rd Qu.:255.3  
#>  Max.   :275.1  
#>  NA's   :61995  
#> dimension(s):
#>      from  to offset   delta  refsys point                      values x/y
#> lon     1 214     NA      NA  WGS 84    NA [214] -73.6234,...,-49.4726 [x]
#> lat     1  44     NA      NA  WGS 84    NA      [44] 56.44,...,61.2056 [y]
#> lev     1   5 1012.5     -25      NA    NA                        NULL    
#> time    1   3   <NA> NA secs POSIXct    NA                        NULL
```

<sup>Created on 2021-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
Thanks!

**Pull request merged**
