### PR TITLE
Update tic

### PR DESCRIPTION
**Pull request by pat-s**
and tidy DESCRIPTION.

The error when building `blog1.Rmd` is `stars` related? Leaving it to you @edzer 

Besides, I am confident that the `tic` implementation will work. You can use this branch to patch the vignette issue (I cannot reproduce it locally).

### CODE REVIEW

**Comment by pat-s** [comment]
Yes, I already opened an issue. Once its solved the issue should clear itself due to the GH installation. 

https://github.com/ropenscilabs/tic/issues/89

**Comment by pat-s** [comment]
With the newest `tic` version I see an error in the vignette: https://travis-ci.org/pat-s/stars/jobs/428601093

Also, I added `rgdal` to suggests as otherwise travis complains about its missingness when building the vignettes. 

The deployment issues have been fixed.

**Comment by edzer** [comment]
Hi @pat-s , would you be able to help me decipher what [this](https://travis-ci.org/r-spatial/stars/jobs/561808563) error message means (git commit/push of gh-pages during tic step)?

**Comment by pat-s** [comment]
No PC access until Wednesday. What are you trying to achieve?
There is also tic::ci_on_travis that you can try.

I just took a quick look on the phone.

**Comment by edzer** [comment]
Thanks - no hurries!

I am trying to achieve that the README.Rmd is rendered correctly; tic/pkgdown wants to generate the `.md` too but then messes up figure paths, it seems; see https://github.com/ropenscilabs/tic/issues/175 - I'm now trying to work around this.

**Pull request merged**
