### PR TITLE
remove functions that duplicate ncmeta funcionality

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
Started perusing the `read_ncdf` and noticed these functions that duplicate what's available over in `ncmeta`. I'll have more as I dig in a bit more. Do you prefer small PRs that encapsulate a single modification like this or should I load up a bit more change?

p.s. I think it would be a good idea to better test the bounds stuff. Should we pull in some sample data from #133 ? I need to get into the stars data package and maybe look at adding some test cases over there?

### CODE REVIEW

**Comment by mdsumner** [comment]
I'm afraid we can't assume there's a "bounds" attribute, but I'm looking closely at your PR and will use it to update in my fork. At the moment I'm working in "mdsumner/stars@mdsumner-dev". 
For example, I have a file with

```R
## nc being nc_meta(file)
nc$attribute %>% dplyr::filter(variable == "temp")
# A tibble: 6 x 3
  attribute   variable value    
  <chr>       <chr>    <list>   
1 long_name   temp     <chr [1]>
2 units       temp     <chr [1]>
3 time        temp     <chr [1]>
4 coordinates temp     <chr [1]>
5 field       temp     <chr [1]>
6 _FillValue  temp     <dbl [1]>
```

I'm not sure we can even assume units is in there, but I'll have a look around.

**Comment by dblodgett-usgs** [comment]
Right. That's why there is a check to make sure `length() > 0` because if they don't exist, they come back `character(0)`.

**Comment by mdsumner** [comment]
Apologies, I haven't gotten to the bottom of what the issue was, but it doesn't work as is. It's very hard for me to incorporate, you happen to have worked on this exactly while I was getting back into it -  I'll definitely follow your lead here though, it just has to stay outside in my own copy for now.

**Comment by dblodgett-usgs** [comment]
OK -- I'm really not following the problem here. Over in that branch you haven't touched the code that I modified here. I'll close this and wait till you've finished before trying any further contribution.

**Comment by mdsumner** [comment]
I believe I have integrated everything now - I've set up https://github.com/mdsumner/stars with default "netcdf-dev" branch. 

The main problems were with units and time interpretation, I've made it more robust now with

* `make_cal_time()` function to isolate the time interpretation
* `make_time` argument to allow opt-out of time interpretation
* time interpretation now robust to no "time" variable (even if there is a "time" dimension)
* `make_units` argument to allow opt out of units interpretation
* more robust to unknown units

I can now `read_ncdf()` on every file in https://github.com/mdsumner/rasterwise *except* for the very large data variable of https://github.com/r-spatial/stars/issues/169#issuecomment-486021814 and for Argo variables with NC_CHAR type (that is handled better in tidync). 

I plan to merge this back into stars master when I'm sure there's no regressions, then look at using tidync to allow easier sub-slicing at the user-level and make `proxy = TRUE` the default.

Can I ask that you work with branches in your fork (not master) and submit PRs against netcdf-dev in my fork when it applies to the ncdf.R file?    It's not ideal but I'm working to make this easier, thanks!

**Pull request closed without merging**
