### PR TITLE
install dev version of pak (#575)

### PR DESCRIPTION
**Pull request by kadyb**
This works on Ubuntu

### CODE REVIEW

**Comment by edzer** [comment]
Great - nearly there! I tried
```r
> tic::use_ghactions_deploy()
ℹ Querying GitHub deploy keys from repo.
✔ Setting active project to '/home/edzer/git/stars'
→ Deploy keys for GitHub Actions already present. No action required.
```
so don't understand why pkgdown stuff isn't uploaded (ubuntu/release). Any idea?

**Comment by kadyb** [comment]
I see pkgdown was recently updated [here](https://github.com/r-spatial/stars/actions/runs/3392620964/jobs/5639025373). After that, none of the workflows were successful. So now we are waiting for [this](https://github.com/r-spatial/stars/actions/runs/3393473678).

**Comment by kadyb** [comment]
pkdwon [worked](https://github.com/r-spatial/stars/actions/runs/3393604333)

**Comment by edzer** [comment]
Oh fantastic, thanks - this may have been a one-off!

**Comment by kadyb** [comment]
There is one more problem with installing starsdata. One time it doesn't work on Ubuntu and another time on macOS.

```
error in pak subprocess
Cannot install packages:
* deps::/home/runner/work/stars/stars: Can't install dependency starsdata
* starsdata: Can't find package called starsdata.
```

**Comment by edzer** [comment]
Might be the timeout issue. Is there some way of setting that, maybe globally?

**Comment by kadyb** [comment]
Tried this, but it doesn't seem to work: https://github.com/kadyb/stars/commit/86e48b7da0fa86f01a9d2f7b7545d30a2ad315d9
Now I'm waiting for the results of this: https://github.com/kadyb/stars/commit/c1e90c0817744adc70d1e5500c92dff016997e61

**Pull request merged**
