### PR TITLE
add `get_blocks()` to specify raster blocks

### PR DESCRIPTION
**Pull request by kadyb**
```r
system.time({x = get_blocks(100000, 100000, 32, 32)})
#> user  system elapsed 
#> 4.13    0.11    4.22
nrow(x)
#> 9765625
head(x)
#>      nXOff nYOff nXSize nYSize
#> [1,]     1     1     32     32
#> [2,]     1    33     32     32
#> [3,]     1    65     32     32
#> [4,]     1    97     32     32
#> [5,]     1   129     32     32
#> [6,]     1   161     32     32
```

Example on raster data:

```r
tif = system.file("tif/L7_ETMs.tif", package = "stars")
r = read_stars(tif, proxy = TRUE)
dim(r)
#>    x    y band
#> 349  352    6 
blocks = get_blocks(nrow(r), ncol(r), 256, 256)
for (i in seq_len(nrow(blocks))) {
  x = read_stars(tif, proxy = FALSE, RasterIO = blocks[i, ])
  print(unname(dim(x)))
}
#> [1] 256 256   6
#> [1] 256  96   6
#> [1]  93 256   6
#> [1]  93  96   6
```

### CODE REVIEW

**Comment by edzer** [comment]
Thanks! You could simplify the example code to
```r
for (i in seq_len(nrow(blocks))) {
  x = read_stars(tif, proxy = FALSE, RasterIO = blocks[i,])
  print(unname(dim(x)))
}
```
because a `data.frame` is a `list`. Before we cement this, can we think of a better name? `st_tile()`? `get_block_parameters()`? 

Can we also have it compute `nBufXSize`, `nBufYSize` to retrieve lower-resolution chunks (I know: feature request)?

**Comment by edzer** [comment]
I was also reading [this](https://www.cogeo.org/in-depth.html) and [this](https://gdal.org/api/gdalrasterband_cpp.html#classGDALRasterBand_1a09e1d83971ddff0b43deffd54ef25eef) - it means that GDAL can tell you what a good blocking will be given a raster file (default: lines, but e.g. for COGs the tile size). Would that be interesting to interface?

**Comment by edzer** [comment]
The `write_stars()` method for `stars_proxy` objects could use this for setting the default chunk size.

**Comment by edzer** [comment]
For instance, 
```
gdalinfo http://s3.eu-central-1.wasabisys.com/eumap/lcv/lcv_landcover.hcl_lucas.corine.rf_p_30m_0..0cm_2019_eumap_epsg3035_v0.1.tif
```
gives

```
Driver: GTiff/GeoTIFF
Files: none associated
Size is 188000, 151000
...
Band 1 Block=1024x1024 Type=Byte, ColorInterp=Gray
  NoData Value=0
  Overviews: 94000x75500, 47000x37750, 23500x18875, 11750x9438, 5875x4719, 2938x2360, 1469x1180, 735x590
```
suggests to use 1024 x 1024. It would be rather trivial to add nBlockXSize and nBlockYSize when reading image metadata (`read_stars`); we need to think where to put this info in a `stars` object.

**Comment by edzer** [comment]
We now have
```r
library(stars)
# Loading required package: abind
# Loading required package: sf
# Linking to GEOS 3.9.1, GDAL 3.3.2, PROJ 7.2.1; sf_use_s2() is TRUE
r = read_stars(stars_sentinel2[[1]]())
attr(st_dimensions(r), "raster")$blocksizes
#      [,1] [,2]
# [1,]  128  128
# [2,]  128  128
# [3,]  128  128
# [4,]  128  128
```

**Comment by kadyb** [comment]
> Before we cement this, can we think of a better name? `st_tile()`?

`st_tile()` sounds great. Here are analogous functions from other software: [GRASS](https://grass.osgeo.org/grass78/manuals/r.tile.html), [SAGA](http://www.saga-gis.org/saga_tool_doc/8.1.0/grid_tools_27.html), [GDAL](https://gdal.org/programs/gdal_retile.html). As a result, they return a saved tiles on disk, so I will add such an example to the documentation. I think we should add the `overlap` argument as well, and perhaps parallelization as example (?).

> Can we also have it compute `nBufXSize`, `nBufYSize` to retrieve lower-resolution chunks (I know: feature request)?

I didn't think about it. Let's leave it for later.

> I was also reading this and this - it means that GDAL can tell you what a good blocking will be given a raster file (default: lines, but e.g. for COGs the tile size).

I saw that recently Dan Baston has dealt with tile size optimization and his experience can be valuable: https://github.com/isciences/exactextractr/issues/62. I wonder how `{terra}` handles it.

**Comment by edzer** [comment]
> I wonder how {terra} handles it.

https://github.com/rspatial/terra/blob/master/src/read_gdal.cpp#L654-L656

**Comment by edzer** [comment]
Great work, thanks!

**Pull request merged**
