### PR TITLE
Accept `read_stars()` input outside the working directory

### PR DESCRIPTION
**Pull request by uribo**
## Summary 

Currently `read_stars()` does not accept input of non-normalized file. Therefore, `normalizePath()` is performed on the input file name.

### ❌ Problem

``` r
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.5.1, GDAL 2.1.2, PROJ 4.9.3

getwd()
#> [1] "/tmp/RtmpgIBAUs/reprex1173a8b189d"
# 1/3: Example code is successful
tif <- 
  system.file("tif/L7_ETMs.tif", package = "stars")
read_stars(tif)
#> stars object with 3 dimensions and 1 attribute
#> attribute(s):
#>   L7_ETMs.tif    
#>  Min.   :  1.00  
#>  1st Qu.: 54.00  
#>  Median : 69.00  
#>  Mean   : 68.91  
#>  3rd Qu.: 86.00  
#>  Max.   :255.00  
#> dimension(s):
#>      from  to  offset delta                       refsys point values
#> x       1 349  288776  28.5 +proj=utm +zone=25 +south... FALSE   NULL
#> y       1 352 9120761 -28.5 +proj=utm +zone=25 +south... FALSE   NULL
#> band    1   6      NA    NA                           NA    NA   NULL

# 2/3: No problem which, input file is exist in working directory.
file.copy(tif, basename(tif))
#> [1] TRUE
read_stars(basename(tif))
#> stars object with 3 dimensions and 1 attribute
#> attribute(s):
#>   L7_ETMs.tif    
#>  Min.   :  1.00  
#>  1st Qu.: 54.00  
#>  Median : 69.00  
#>  Mean   : 68.91  
#>  3rd Qu.: 86.00  
#>  Max.   :255.00  
#> dimension(s):
#>      from  to  offset delta                       refsys point values
#> x       1 349  288776  28.5 +proj=utm +zone=25 +south... FALSE   NULL
#> y       1 352 9120761 -28.5 +proj=utm +zone=25 +south... FALSE   NULL
#> band    1   6      NA    NA                           NA    NA   NULL


# 3/3: However un-successful when input file existing out-of-directory
file.copy(tif, paste0("~/", basename(tif)))
#> [1] FALSE
(new_loc <- 
  paste0("~/", basename(tif)))
#> [1] "~/L7_ETMs.tif"
file.exists(new_loc)
#> [1] TRUE

read_stars(new_loc)
#> trying to read file: ~/L7_ETMs.tif
#> Error in CPL_read_gdal(as.character(x), as.character(options), as.character(driver), : file not found
```

<sup>Created on 2018-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### 🔰 Update

``` r
library(stars)
tif <-
  system.file("tif/L7_ETMs.tif", package = "stars")

file.copy(tif, paste0("~/", basename(tif)))
(new_loc <-
  paste0("~/", basename(tif)))
#> [1] "~/L7_ETMs.tif"
file.exists(new_loc)
#> [1] TRUE

read_stars(new_loc)
#> stars object with 3 dimensions and 1 attribute
#> attribute(s):
#>   L7_ETMs.tif    
#>  Min.   :  1.00  
#>  1st Qu.: 54.00  
#>  Median : 69.00  
#>  Mean   : 68.91  
#>  3rd Qu.: 86.00  
#>  Max.   :255.00  
#> dimension(s):
#>      from  to  offset delta                       refsys point values    
#> x       1 349  288776  28.5 +proj=utm +zone=25 +south... FALSE   NULL [x]
#> y       1 352 9120761 -28.5 +proj=utm +zone=25 +south... FALSE   NULL [y]
#> band    1   6      NA    NA                           NA    NA   NULL
```

<sup>Created on 2018-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

## Related issues

I also add `enc2utf8()` processing for running on windows 

https://github.com/r-spatial/sf/pull/471

 (but I have not been able to verify that this is correct)

### CODE REVIEW

**Comment by edzer** [comment]
Thanks - good thinking!

**Comment by mdsumner** [comment]
Just might need a caveat for warnings from `normalizePath` because subdatasets: 

```R
x <- "NETCDF:\"inst/nc/reduced.nc\":sst"
normalizePath(x)  ## use mustWork = FALSE to avoid warning
#[1] "NETCDF:\"inst/nc/reduced.nc\":sst"
#Warning message:
#In normalizePath(x) :
#  path[1]="NETCDF:"inst/nc/reduced.nc":sst": No such file or directory
```

It still won't work if `x <- "NETCDF:\"~/reduced.nc\":sst"` which is probably fair enough.

**Comment by edzer** [comment]
Is adding `mustWork=FALSE` to it sufficient?

**Comment by mdsumner** [comment]
Pretty sure!   I just can't try this on anything but linux right now

**Comment by ChuliangXiao** [comment]
I was trying to replicate the case of [Curvilinear grids](https://r-spatial.github.io/stars/articles/data_model.html) and encountered similar issue `Error in CPL_read_gdal`.
``` r
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
(s5p = system.file("sentinel5p/S5P_NRTI_L2__NO2____20180717T120113_20180717T120613_03932_01_010002_20180717T125231.nc", package = "starsdata"))
#> [1] "C:/Users/xiao/Documents/R/win-library/3.5/starsdata/sentinel5p/S5P_NRTI_L2__NO2____20180717T120113_20180717T120613_03932_01_010002_20180717T125231.nc"

lat_ds = paste0("HDF5:\"", s5p, "\"://PRODUCT/latitude")
lon_ds = paste0("HDF5:\"", s5p, "\"://PRODUCT/longitude")
nit_ds = paste0("HDF5:\"", s5p, "\"://PRODUCT/SUPPORT_DATA/DETAILED_RESULTS/nitrogendioxide_summed_total_column")
lat = read_stars(lat_ds)
#> trying to read file: C:\Users\xiao\AppData\Local\Temp\1\RtmpQpmhAv\reprex4a441e9b629a\HDF5:"C:\Users\xiao\Documents\R\win-library\3.5\starsdata\sentinel5p\S5P_NRTI_L2__NO2____20180717T120113_20180717T120613_03932_01_010002_20180717T125231.nc":\PRODUCT\latitude
#> Error in CPL_read_gdal(as.character(x), as.character(options), as.character(driver), : file not found
lon = read_stars(lon_ds)
#> trying to read file: C:\Users\xiao\AppData\Local\Temp\1\RtmpQpmhAv\reprex4a441e9b629a\HDF5:"C:\Users\xiao\Documents\R\win-library\3.5\starsdata\sentinel5p\S5P_NRTI_L2__NO2____20180717T120113_20180717T120613_03932_01_010002_20180717T125231.nc":\PRODUCT\longitude
#> Error in CPL_read_gdal(as.character(x), as.character(options), as.character(driver), : file not found
nit = read_stars(nit_ds)
#> Warning in get_raster(affine = pr$geotransform[c(3, 5)], dimensions =
#> c("x", : setting NA affine values to zero
```

<sup>Created on 2018-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>


``` r
sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] rgdal_1.3-6    sp_1.3-1       bindrcpp_0.2.2 mapview_2.6.0  tidync_0.0.3   stars_0.2-1    sf_0.7-2      
 [8] abind_1.4-5    usethis_1.4.0  devtools_2.0.1

loaded via a namespace (and not attached):
 [1] pkgload_1.0.2     viridisLite_0.3.0 shiny_1.2.0       assertthat_0.2.0  stats4_3.5.1      yaml_2.2.0       
 [7] remotes_2.0.2     sessioninfo_1.1.1 pillar_1.3.0      backports_1.1.2   lattice_0.20-38   glue_1.3.0       
[13] digest_0.6.18     promises_1.0.1    colorspace_1.3-2  htmltools_0.3.6   httpuv_1.4.5      clipr_0.4.1      
[19] pkgconfig_2.0.2   raster_2.8-4      purrr_0.2.5       xtable_1.8-3      scales_1.0.0      webshot_0.5.1    
[25] processx_3.2.0    whisker_0.3-2     satellite_1.0.1   later_0.7.5       tibble_1.4.2      withr_2.1.2      
[31] repr_0.18         cli_1.0.1         magrittr_1.5      crayon_1.3.4      mime_0.6          evaluate_0.12    
[37] memoise_1.1.0     ps_1.2.1          fs_1.2.6          ncdf4_1.16        fansi_0.4.0       forcats_0.3.0    
[43] class_7.3-14      pkgbuild_1.0.2    tools_3.5.1       prettyunits_1.0.2 reprex_0.2.1      munsell_0.5.0    
[49] callr_3.0.0       compiler_3.5.1    e1071_1.7-0       RNetCDF_1.9-1     rlang_0.3.0.1     classInt_0.2-3   
[55] debugme_1.1.0     units_0.6-1       grid_3.5.1        rstudioapi_0.8    htmlwidgets_1.3   crosstalk_1.0.0  
[61] rmarkdown_1.10    base64enc_0.1-3   testthat_2.0.1    codetools_0.2-15  DBI_1.0.0         curl_3.2         
[67] R6_2.3.0          ncmeta_0.0.3      knitr_1.20        dplyr_0.7.8       utf8_1.1.4        bindr_0.1.1      
[73] rprojroot_1.3-2   desc_1.2.0        parallel_3.5.1    Rcpp_1.0.0        png_0.1-7         leaflet_2.0.2    
[79] spData_0.2.9.6    tidyselect_0.2.5 
```

<sup>Created on 2018-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by edzer** [comment]
Do you have the HDF5 driver installed?
```r
> library(sf)
> st_drivers("raster")["HDF5",]
     name                          long_name write  copy is_raster is_vector
HDF5 HDF5 Hierarchical Data Format Release 5 FALSE FALSE      TRUE     FALSE
       vsi
HDF5 FALSE
```

**Comment by ChuliangXiao** [comment]
```
lat = read_stars(lat_ds)
lon = read_stars(lon_ds)
nit = read_stars(nit_ds)
```
In the above, `nit = read_stars(nit_ds)` is good, but `lat = read_stars(lat_ds)` has errors.

```
> library(sf)
> st_drivers("raster")["HDF5",]
     name                          long_name write  copy is_raster is_vector   vsi
HDF5 HDF5 Hierarchical Data Format Release 5 FALSE FALSE      TRUE     FALSE FALSE
```

**Comment by edzer** [comment]
Mmm, no problems here; can someone with a windows machine reproduce this problem?

**Comment by ChuliangXiao** [comment]
> Mmm, no problems here; can someone with a windows machine reproduce this problem?

https://github.com/r-spatial/stars/issues/54#issuecomment-422325910
Looks @adrfantini had a similar issue, `read_stars()` cannot read coordinates of curvilinear grids.
```r
library(stars)
hmr = '/dev/shm/hmr.nc'
lat = read_stars(hmr, sub='lat') #Does not work, reads 'pr' instead. Separate issue?
library(raster) #Let's use raster to get the data in then
lat = raster(hmr, varname = 'lat') %>% st_as_stars %>% adrop
lon = raster(hmr, varname = 'lon') %>% st_as_stars %>% adrop
nit = read_stars(hmr) %>% adrop
ll = setNames(c(lon, lat), c("x", "y"))
nit.c = st_as_stars(nit, curvilinear = ll)
st_crs(nit.c) = 4326
plot(nit.c, breaks = "equal", reset = FALSE, axes = TRUE, as_points = FALSE, border = NA)
library(rnaturalearth)
plot(st_geometry(ne_countries(scale = "medium", returnclass="sf")), add = TRUE, border = 'grey')
```

**Comment by adrfantini** [comment]
@ChuliangXiao 
I'm not sure that's related, also, I do not use Windows machines with R.

**Comment by ChuliangXiao** [comment]
@adrfantini  Thanks for your input. I thought you meant `read_stars()` didn't work with read coordinates like`lat`.
```r
lat = read_stars(hmr, sub='lat') #Does not work, reads 'pr' instead. Separate issue?
```

**Comment by edzer** [comment]
What is the maximum path length on your machine?

**Comment by ChuliangXiao** [comment]
> What is the maximum path length on your machine?

This is what I get from [docs.microsoft.com](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file)

> ### Maximum Path Length Limitation
In the Windows API (with some exceptions discussed in the following paragraphs), the maximum length for a path is MAX_PATH, which is defined as 260 characters. A local path is structured in the following order: drive letter, colon, backslash, name components separated by backslashes, and a terminating null character. For example, the maximum path on drive D is "D:\some 256-character path string" where "" represents the invisible terminating null character for the current system codepage. (The characters < > are used here for visual clarity and cannot be part of a valid path string.)

**Pull request merged**
